
syntax = "proto3";
package xlabs.tsscommon.service.signer;
option go_package = "./service/signer;signer";
import "google/protobuf/any.proto";
import "proto/io.proto";


service Signer {
  // SignMessage is a bidirectional streaming RPC to sign a message digest using TSS.
  // The client sends a stream of SignRequest messages containing the digest to be signed,
  // the protocol type, and the committee members involved in the signing process.
  // The server responds with a stream of SignResponse messages containing either
  // the signature data or the status (on failure).
  rpc SignMessage (stream SignRequest) returns (stream SignResponse);

  // GetPublicData is a unary RPC, providing the requester with the signer's 
  // public data (all of its public keys).
  rpc GetPublicData(PublicDataRequest) returns (PublicData);

  // VerifySignature is a unary RPC that verifies a signature against the provided public data.
  // Namely, the signature can be valid, but it may have been signed by a
  // different signer service with different public data.
  rpc VerifySignature(VerifySignatureRequest) returns (VerifySignatureResponse);
}


message SignRequest {
  // A 32-byte digest to be signed.
  bytes digest = 1;
  // Defines the protocol type. E.g., ProtocolFROSTSign.ToString() (see protocol.go)
  string protocol = 2;
  // The committee members involved in the signing process. 
  // Each member should be an Ethereum address.
  repeated bytes committee = 3; 
}

message SignResponse {
  oneof response {
    // can be translated to either frost or ecdsa signature. depends on the protocol used.
    SignatureData signature = 1; // M represents the SignRequest.digest.
    SignStatus status = 2;
  }
}

message SignStatus {
  // The status code, which should be an enum value of
  // [google.rpc.Code][google.rpc.Code].
  int32 code = 1;

  // A developer-facing error message, which should be in English. Any
  // user-facing error message should be localized and sent in the
  // [google.rpc.Status.details][google.rpc.Status.details] field, or localized
  // by the client.
  string message = 2;

  // The digest from the SignRequest.
  bytes digest = 3;
  // The protocol from the SignRequest.
  string protocol = 4;

  // optional additional details message.
  google.protobuf.Any details = 5;
}

// ErrorDetails contains additional information about an error that occurred during the signing process.
message ErrorDetails {
	string task=1; // e.g., function name where the error occurred
	int32 round=2; // -1 if not applicable
  repeated PartyID culprits=3; // parties responsible for the error. Optional.
}

// WarningDetails contains information about a warning that occurred during the signing process.
message WarningDetails {
	repeated PartyID culprits = 1;
	int32    round = 2;
}

message PublicDataRequest {}

message PublicData {
  // the frost public data is a public key for schnorr-based FROST signatures that are adjusted to 
  // EVM's ecrecover.
  bytes frost_public_data = 1;
  // the ecdsa public data is a public key for ecdsa-based signatures.
  bytes ecdsa_public_data = 2;
}

message VerifySignatureRequest {
  SignatureData signature = 1;
  // PublicData the signature should be verified against.
  // NOTE, a signature can be valid but not the output of the requested signer.
  PublicData public_data = 2;
}

message VerifySignatureResponse {
  bool is_valid = 1;
}