// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/signer.proto

package signer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Signer_SignMessage_FullMethodName     = "/xlabs.tsscommon.service.signer.Signer/SignMessage"
	Signer_GetPublicData_FullMethodName   = "/xlabs.tsscommon.service.signer.Signer/GetPublicData"
	Signer_VerifySignature_FullMethodName = "/xlabs.tsscommon.service.signer.Signer/VerifySignature"
)

// SignerClient is the client API for Signer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignerClient interface {
	// SignMessage is a bidirectional streaming RPC to sign a message digest using TSS.
	// The client sends a stream of SignRequest messages containing the digest to be signed,
	// the protocol type, and the committee members involved in the signing process.
	// The server responds with a stream of SignResponse messages containing either
	// the signature data or the status (on failure).
	SignMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SignRequest, SignResponse], error)
	// GetPublicData is a unary RPC, providing the requester with the signer's
	// public data (all of its public keys).
	GetPublicData(ctx context.Context, in *PublicDataRequest, opts ...grpc.CallOption) (*PublicData, error)
	// VerifySignature is a unary RPC that verifies a signature against the provided public data.
	// Namely, the signature can be valid, but it may have been signed by a
	// different signer service with different public data.
	VerifySignature(ctx context.Context, in *VerifySignatureRequest, opts ...grpc.CallOption) (*VerifySignatureResponse, error)
}

type signerClient struct {
	cc grpc.ClientConnInterface
}

func NewSignerClient(cc grpc.ClientConnInterface) SignerClient {
	return &signerClient{cc}
}

func (c *signerClient) SignMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SignRequest, SignResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Signer_ServiceDesc.Streams[0], Signer_SignMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SignRequest, SignResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Signer_SignMessageClient = grpc.BidiStreamingClient[SignRequest, SignResponse]

func (c *signerClient) GetPublicData(ctx context.Context, in *PublicDataRequest, opts ...grpc.CallOption) (*PublicData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicData)
	err := c.cc.Invoke(ctx, Signer_GetPublicData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signerClient) VerifySignature(ctx context.Context, in *VerifySignatureRequest, opts ...grpc.CallOption) (*VerifySignatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySignatureResponse)
	err := c.cc.Invoke(ctx, Signer_VerifySignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignerServer is the server API for Signer service.
// All implementations must embed UnimplementedSignerServer
// for forward compatibility.
type SignerServer interface {
	// SignMessage is a bidirectional streaming RPC to sign a message digest using TSS.
	// The client sends a stream of SignRequest messages containing the digest to be signed,
	// the protocol type, and the committee members involved in the signing process.
	// The server responds with a stream of SignResponse messages containing either
	// the signature data or the status (on failure).
	SignMessage(grpc.BidiStreamingServer[SignRequest, SignResponse]) error
	// GetPublicData is a unary RPC, providing the requester with the signer's
	// public data (all of its public keys).
	GetPublicData(context.Context, *PublicDataRequest) (*PublicData, error)
	// VerifySignature is a unary RPC that verifies a signature against the provided public data.
	// Namely, the signature can be valid, but it may have been signed by a
	// different signer service with different public data.
	VerifySignature(context.Context, *VerifySignatureRequest) (*VerifySignatureResponse, error)
	mustEmbedUnimplementedSignerServer()
}

// UnimplementedSignerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignerServer struct{}

func (UnimplementedSignerServer) SignMessage(grpc.BidiStreamingServer[SignRequest, SignResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SignMessage not implemented")
}
func (UnimplementedSignerServer) GetPublicData(context.Context, *PublicDataRequest) (*PublicData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicData not implemented")
}
func (UnimplementedSignerServer) VerifySignature(context.Context, *VerifySignatureRequest) (*VerifySignatureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifySignature not implemented")
}
func (UnimplementedSignerServer) mustEmbedUnimplementedSignerServer() {}
func (UnimplementedSignerServer) testEmbeddedByValue()                {}

// UnsafeSignerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignerServer will
// result in compilation errors.
type UnsafeSignerServer interface {
	mustEmbedUnimplementedSignerServer()
}

func RegisterSignerServer(s grpc.ServiceRegistrar, srv SignerServer) {
	// If the following call pancis, it indicates UnimplementedSignerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Signer_ServiceDesc, srv)
}

func _Signer_SignMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SignerServer).SignMessage(&grpc.GenericServerStream[SignRequest, SignResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Signer_SignMessageServer = grpc.BidiStreamingServer[SignRequest, SignResponse]

func _Signer_GetPublicData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServer).GetPublicData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signer_GetPublicData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServer).GetPublicData(ctx, req.(*PublicDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Signer_VerifySignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignerServer).VerifySignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Signer_VerifySignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignerServer).VerifySignature(ctx, req.(*VerifySignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Signer_ServiceDesc is the grpc.ServiceDesc for Signer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Signer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xlabs.tsscommon.service.signer.Signer",
	HandlerType: (*SignerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicData",
			Handler:    _Signer_GetPublicData_Handler,
		},
		{
			MethodName: "VerifySignature",
			Handler:    _Signer_VerifySignature_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SignMessage",
			Handler:       _Signer_SignMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/signer.proto",
}
