// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/signer.proto

package signer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Signer_SignMessage_FullMethodName = "/xlabs.tsscommon.service.signer.Signer/SignMessage"
)

// SignerClient is the client API for Signer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignerClient interface {
	// SignMessage is a bidirectional streaming RPC to sign a message digest using TSS.
	// The client sends a stream of SignRequest messages containing the digest to be signed,
	// the protocol type, and the committee members involved in the signing process.
	// The server responds with a stream of SignResponse messages containing either
	// the signature data or the status (on failure).
	SignMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SignRequest, SignResponse], error)
}

type signerClient struct {
	cc grpc.ClientConnInterface
}

func NewSignerClient(cc grpc.ClientConnInterface) SignerClient {
	return &signerClient{cc}
}

func (c *signerClient) SignMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SignRequest, SignResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Signer_ServiceDesc.Streams[0], Signer_SignMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SignRequest, SignResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Signer_SignMessageClient = grpc.BidiStreamingClient[SignRequest, SignResponse]

// SignerServer is the server API for Signer service.
// All implementations must embed UnimplementedSignerServer
// for forward compatibility.
type SignerServer interface {
	// SignMessage is a bidirectional streaming RPC to sign a message digest using TSS.
	// The client sends a stream of SignRequest messages containing the digest to be signed,
	// the protocol type, and the committee members involved in the signing process.
	// The server responds with a stream of SignResponse messages containing either
	// the signature data or the status (on failure).
	SignMessage(grpc.BidiStreamingServer[SignRequest, SignResponse]) error
	mustEmbedUnimplementedSignerServer()
}

// UnimplementedSignerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignerServer struct{}

func (UnimplementedSignerServer) SignMessage(grpc.BidiStreamingServer[SignRequest, SignResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SignMessage not implemented")
}
func (UnimplementedSignerServer) mustEmbedUnimplementedSignerServer() {}
func (UnimplementedSignerServer) testEmbeddedByValue()                {}

// UnsafeSignerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignerServer will
// result in compilation errors.
type UnsafeSignerServer interface {
	mustEmbedUnimplementedSignerServer()
}

func RegisterSignerServer(s grpc.ServiceRegistrar, srv SignerServer) {
	// If the following call pancis, it indicates UnimplementedSignerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Signer_ServiceDesc, srv)
}

func _Signer_SignMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SignerServer).SignMessage(&grpc.GenericServerStream[SignRequest, SignResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Signer_SignMessageServer = grpc.BidiStreamingServer[SignRequest, SignResponse]

// Signer_ServiceDesc is the grpc.ServiceDesc for Signer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Signer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xlabs.tsscommon.service.signer.Signer",
	HandlerType: (*SignerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SignMessage",
			Handler:       _Signer_SignMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/signer.proto",
}
